package bd6.entity;
// Generated 27/02/2020 17:09:21 by Hibernate Tools 4.3.1



/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private Integer id;
     private Partidas partidas;
     private String moviments;

    public Movimientos() {
    }

    public Movimientos(Partidas partidas, String moviments) {
       this.partidas = partidas;
       this.moviments = moviments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partidas getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Partidas partidas) {
        this.partidas = partidas;
    }
    public String getMoviments() {
        return this.moviments;
    }
    
    public void setMoviments(String moviments) {
        this.moviments = moviments;
    }




}


